### ISSUE TITLE
Problem when searching for artist name

### ISSUE THREAD

**Issue by Alina-enni** [Alina-enni/lingdiggers#29]
It seems to me that when you try searching with an artist name, e.g. "Coldplay", no search results are displayed. It's strange because the matching documents are correct and there should be 5 songs displayed. Will have to look into this.

<img width="1191" alt="Screenshot 2022-03-11 at 0 35 28" src="https://user-images.githubusercontent.com/98087771/157766373-654f907d-b658-49e6-8114-db6186cc7ccc.png">

**Comment by miglamigla** [comment]
The issue was here: 

search = " " + search + " "

It made the query 'coldplay' become ' coldplay ' and that's why it could not find it :D I think it's fixed now, but only for single word search. I tried to do the same for the multi-word search, but it just printed out the same song tens of times, so I just left it as it is.
